### ISSUE TITLE
Configuring upstart... FAILED No such file

### ISSUE THREAD

**Issue by quape** [bordalix/yamup#13]
When doing `yamup setup` on a blank Ubuntu 20.04 (LTS) x64
```
    Configuring upstart
    x Configuring upstart: FAILED
        No such file
```

No problems on 18.04

**Comment by bordalix** [comment]
That's strange, in a Ubuntu 20.04 it should use systemd and not upstart.

This is the script that decides what to use (for backward compatibility):
https://github.com/bordalix/yamup/blame/master/scripts/linux/upstartORsystemd.sh

Do you mind checking if your Ubuntu has in fact the file /etc/os-release?
I change this 6 months ago, do you have the latest version of yamup?

**Comment by quape** [comment]
`lib/taskLists/linux.js`, line 89: `upstartORsystemd.sh` seems to return `upstart`?  I currently do not understand why because it returns `systemd` when I run it manually on the server and `/etc/os-release` exists as well.

**Comment by quape** [comment]
Ok it turned out that I had different versions of yamup in /usr/lib an /usr/local/bin due to a node versions mess. Now it works.
