### ISSUE TITLE
Let'sencrypt support eith nginx / redbird ?

### ISSUE THREAD

**Issue by karlitos** [bordalix/yamup#4]
First of all, thanks for the awesome tool !

I couldn't help but notice, that  the [stud](https://github.com/bumptech/stud) terminator isn't actively developed anymore. Also, I wonder how to setup yamup with Let'sencrypt  and automatic certificate renewal.

Do you think about extending yamup, to support Let'sencrypt directly ?

**Comment by bordalix** [comment]
Yes, yamup can (and should) be used with nginx and let's encrypt.

**1 -** Configure a nginx site with a proxy_pass:

file: /etc/nginx/sites-available/example.com

```
server {
  if ($host = www.example.com) {
    return 301 https://example.com$request_uri;
  } # managed by Certbot

  if ($host = example.com) {
    return 301 https://$host$request_uri;
  } # managed by Certbot

  listen 80;
  server_name example.com www.example.com; 
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  charset UTF-8;
  server_name example.com www.example.com; 

  # meteor app
  location / {
    proxy_pass http://localhost:3001;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}
```

**2 -** Check your nginx configuration sintax:

`sudo nginx -t`

**3 -** Install certbot and generate the certificates:

`sudo certbot --nginx -d example.com -d www.example.com`

It should append this 2 lines to the file:

```
ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
```

**4 -** Reload nginx:

`sudo nginx -s reload`

**5 -** Configure yamup without SSL, and on port 3001.

file: yamup.json

```
{
  // Server authentication info
  "servers": [
    {
      "host": "example.com",
      "username": "aws_username",
      "pem": "aws_pem_file.pem"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": false,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "8.9.1",

  // Install PhantomJS in the server
  "setupPhantom": false,

  // Show a progress bar during the upload of the bundle to the server. 
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "example",

  // Location of app (local directory)
  "app": "./",

  // Configure environment
  "env": {
    "PORT": 3001,
    "ROOT_URL": "https://example.com",
    "MONGO_URL": "mongodb://127.0.0.1/example"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}
```

**6 -** Deploy it with `yamup deploy` or `yamup reconfig` and you should have your site running with SSL via Let's Encrypt.

**7 -** To renew your certificates, just run on the server (you can put it on a cronjob also):

`sudo certbot --nginx renew`

**8 -** If you put the certificate renewal as a cronjob, you don't need to worry any more with SSL and certificates, and you can use yamup to simply build and deploy your Meteor app. Due to this, I don't plan to add support to Let's Encrypt directly.

**Comment by karlitos** [comment]
Hello João, and many thanks for you very detailed instructions.

I actually followed the tutorial from [this gist](https://gist.github.com/cecilemuller/a26737699a7e70a7093d4dc115915de8) which is somehow a little bit more straightforward. The __certbot__ is a very clever piece of software , basically it is enough to create a minimal _nginx_ config like:

**EDITED ON 15.08.2018.**
```shell
# Virtual Host configuration for yourdomain.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#

# we're in the http context here
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

# the Meteor / Node.js app server
server {
       listen 80;
       listen [::]:80;

       server_name yourdomain.com www.yourdomain.com;

       # meteor app
       location / {
          proxy_pass http://localhost:3001;
         # WebSocket proxying - from http://nginx.org/en/docs/http/websocket.html
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
          # recommended with keepalive connections - http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version
          proxy_http_version 1.1;
          # pass the host header - http://wiki.nginx.org/HttpProxyModule#proxy_pass
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_cache_bypass $http_upgrade;
       }
}
```

Then running **certbot** it allows you to automatically set-up Let's Encrypt for all your domains, since __certbot__ parses all _config files_ placed/symlinked in in `/etc/nginx/sites-enabled`

It would be very nice if you could update the README with the instructions or link the gist file.

EDIT: I recognized my mistake with missing necessary configuration lines in the _server - location_ block, which are necessary for the Websockets working properly and updated the configuration file.

**Comment by bordalix** [comment]
Updated the README and added the gist link.
