### ISSUE TITLE
manipulate app bundle before upload

### ISSUE THREAD

**Issue by quape** [bordalix/yamup#8]
Hi there,
is it possible to make changes to the bundle before uploading it to the server? I want to strip html comments as these are not removed for production.

**Comment by bordalix** [comment]
That's not a job for yamup. That should be done by meteor on the build process.

**Comment by quape** [comment]
Well, Meteor is not doing that so my question was if I could solve it through yamup at least. Or somewhere else?

**Comment by bordalix** [comment]
Have you seen this? https://guide.meteor.com/build-tool.html#concatenate-and-minify

**Comment by quape** [comment]
Yes, this minifies js and css but leaves html untouched.
